In [ ]:
import numpy as np
totaldata=np.load("/content/drive/MyDrive/J2/hourlytotalarray_withpm10.npy",allow_pickle=True)


In [ ]:
pm25=totaldata[:,:,0]
pm10=totaldata[:,:,-1]

In [ ]:
np.max(pm10)

318.812344234757

In [ ]:
import pandas as pd
ar=pd.read_csv('/content/drive/MyDrive/J2/data/station (copy).csv')
loc_b=pd.DataFrame(ar)

In [ ]:
meanpm25=np.mean(pm25,0)

In [ ]:
meanpm10=np.mean(pm10,0)

In [ ]:
meanpm10/meanpm25

array([1.9630863374855159, 2.167943665503659, 1.948233497471488,
       2.0309928990252506, 2.026519763224703, 2.0869193005738724,
       2.196737806255485, 2.5666259724438008, 1.9414037329269513,
       1.9460245467495456, 2.3380544291868013, 2.0328194578557204,
       2.1073933695112075, 2.3457839116726356, 1.6642184550416879,
       1.917804593494209, 1.9789176024373107, 1.7846574802556787,
       2.115338387281252, 1.9664791801942307, 1.8149197309568736,
       2.0849800561563883, 2.267607937420634, 1.9546755797289457,
       2.0878519370124957, 1.764102512199602, 1.9498450022457734,
       2.1628899023195376, 1.7878981268492564, 1.8715347857489733,
       2.168735688247559, 2.006555301240389, 1.900383522295853,
       1.981601293915619, 2.679396930084914, 2.1444816650367677,
       2.007989942373017, 1.7081986895518106, 1.93336644479169,
       2.1670008245729147], dtype=object)

In [ ]:
pm10csv=pd.read_csv('/content/drive/MyDrive/J2/data/cleanpm10.csv')
# pm10mean=np.mean(np.asarray(pm10csv),0)

In [ ]:
pm10csv=pm10csv.iloc[:,2:]

In [ ]:
pm10csv

Alipur..Delhi...DPCC  Anand.Vihar..Delhi...DPCC  \
0                     344.0                 771.874752   
1                     312.0                 660.000000   
2                     312.0                 660.000000   
3                     301.0                 514.000000   
4                     301.0                 514.000000   
...                     ...                        ...   
52603                 189.0                 300.000000   
52604                 188.0                 300.000000   
52605                 188.0                 244.000000   
52606                 186.0                 244.000000   
52607                 186.0                 266.000000   

       Ashok.Vihar..Delhi...DPCC  Aya.Nagar..Delhi...IMD  \
0                          965.0                  537.24   
1                          554.0                  533.12   
2                          554.0                  679.15   
3                          450.0                  893.24   
4                          450.0                  805.27   
...                          ...                     ...   
52603                      232.0                  145.93   
52604                      232.0                  161.49   
52605                      271.0                  126.21   
52606                      271.0                  129.73   
52607                      206.0                  113.21   

       Bawana..Delhi...DPCC  Burari.Crossing..Delhi...IMD  \
0                723.111504                    751.240449   
1                668.072097                    639.112284   
2                951.000000                    590.858425   
3                951.000000                    529.433363   
4                856.000000                    515.450364   
...                     ...                           ...   
52603            260.000000                    243.907505   
52604            260.000000                    250.306375   
52605            373.000000                    262.142807   
52606            373.000000                    261.791316   
52607            289.000000                    246.945315   

       CRRI.Mathura.Road..Delhi...IMD  Chandni.Chowk..Delhi...IITM  \
0                          763.043775                   791.680475   
1                          770.620754                   774.176307   
2                          753.355056                   738.860914   
3                          994.320000                   673.566395   
4                          998.870000                   637.364772   
...                               ...                          ...   
52603                      159.740000                   200.500000   
52604                      271.190000                   204.100000   
52605                      175.030000                   203.900000   
52606                      215.660000                   211.100000   
52607                      295.540000                   214.200000   

       DTU..Delhi...CPCB  Dr..Karni.Singh.Shooting.Range..Delhi...DPCC  ...  \
0                  756.0                                    926.000000  ...   
1                  756.0                                    926.000000  ...   
2                  570.0                                    730.416657  ...   
3                  570.0                                    974.000000  ...   
4                  424.0                                    974.000000  ...   
...                  ...                                           ...  ...   
52603              215.0                                    174.000000  ...   
52604              318.0                                    174.000000  ...   
52605              318.0                                    188.000000  ...   
52606              350.0                                    188.000000  ...   
52607              350.0                                    201.000000  ...   

       Pusa..Delhi...DPCC  Pusa..Delhi...IMD  R.K.Puram..Delhi...D

In [ ]:
pm10mean=np.mean(np.asarray(pm10csv),0)

In [ ]:
pm10mean

array([202.12049965, 259.47548082, 209.28510176, 152.44801274,
       243.09993779, 209.54666114, 206.87541315, 228.94397824,
       209.74838965, 176.58715225, 238.73350013, 210.35705146,
       176.15404787, 203.58463821, 178.97618303, 246.320984  ,
       182.23008533, 153.82304374, 159.83400821, 186.25596269,
       164.93632025, 247.07710077, 217.01125158, 159.83728807,
       229.97978142, 200.22187477, 178.23991198, 210.39283783,
       189.90405156, 204.60975317, 199.2288881 , 162.88707369,
       188.27155402, 227.11915048, 215.20010861, 199.24921236,
       215.31363508, 143.18602188, 221.57116797, 235.67093179])

In [ ]:
pm10new=[]
for i in range(26280):
  s=2*i
  # print(s)
  new=np.expand_dims(np.mean(pm10csv[s:s+2],axis=0),axis=0)
  pm10new.append(new)
pm10new=np.concatenate(pm10new,0)

In [ ]:
pm10mean1=np.mean(pm10new,0)
pm10mean1

array([202.11650011, 259.42743064, 209.2517434 , 152.41573676,
       243.10107548, 209.50326376, 206.82950029, 228.9104447 ,
       209.70355022, 176.53877294, 238.73662433, 210.31786905,
       176.1643752 , 203.58709374, 179.01986372, 246.27633802,
       182.16625435, 153.78239348, 159.788525  , 186.21340725,
       164.8855239 , 247.01697331, 216.97782007, 159.82549564,
       229.98484286, 200.15364132, 178.23111414, 210.34871409,
       189.82681401, 204.57447589, 199.13147536, 162.85871334,
       188.23191853, 227.10940389, 215.14214258, 199.18353431,
       215.29162318, 143.11986756, 221.48439886, 235.63250342])

In [ ]:
def doKmeans(X, nclust=8):
    model = KMeans(nclust)
    model.fit(X)
    clust_labels = model.predict(X)
    cent = model.cluster_centers_
    return (clust_labels, cent)

clust_labels, cent = doKmeans(pm25, 3)
# kmeans = pd.DataFrame(clust_labels)
# print(kmeans)
pm["kmeans"]=clust_labels

In [ ]:
latlon=loc_b.iloc[:,1:]

In [ ]:
meanpm25.shape

(40,)

In [ ]:
dataapm25=np.concatenate([np.asarray(latlon),np.expand_dims(meanpm25,-1)],-1)

In [ ]:
dataapm10=np.concatenate([np.asarray(latlon),np.expand_dims(meanpm10,-1)],-1)

In [ ]:
dataapm25pm10=np.concatenate([dataapm10,np.expand_dims(meanpm25,-1)],-1)

In [ ]:
 from sklearn.cluster import KMeans

In [ ]:
def doKmeans(X, nclust=8):
    model = KMeans(nclust)
    model.fit(X)
    clust_labels = model.predict(X)
    cent = model.cluster_centers_
    return (clust_labels, cent)

clust_labels, cent = doKmeans(dataapm10, 3)
# kmeans = pd.DataFrame(clust_labels)
# print(kmeans)
# pm["kmeans"]=clust_labels

/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [ ]:
clust_labels1, cent = doKmeans(dataapm25, 3)
clust_labels1

/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


array([2, 1, 1, 0, 1, 2, 2, 2, 1, 2, 2, 2, 0, 0, 1, 1, 2, 0, 0, 2, 2, 1,
       2, 0, 1, 1, 2, 2, 1, 1, 2, 0, 2, 1, 0, 2, 1, 0, 1, 1], dtype=int32)

In [ ]:
Cluster0_25=np.where(clust_labels1==0)
Cluster1_25=np.where(clust_labels1==1)
Cluster2_25=np.where(clust_labels1==2)


In [ ]:
Cluster0_10=np.where(clust_labels==0)
Cluster1_10=np.where(clust_labels==1)
Cluster2_10=np.where(clust_labels==2)

In [ ]:
clust_labels

array([1, 2, 1, 0, 2, 1, 1, 2, 1, 0, 2, 1, 0, 1, 0, 2, 0, 0, 0, 1, 0, 2,
       1, 0, 2, 1, 0, 1, 1, 1, 1, 0, 1, 2, 1, 1, 1, 0, 1, 2], dtype=int32)

In [ ]:
clust_labels_combine, cent = doKmeans(dataapm25pm10, 3)
clust_labels_combine

/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


array([0, 2, 0, 1, 2, 0, 0, 0, 0, 1, 2, 0, 1, 0, 1, 2, 1, 1, 1, 0, 1, 2,
       0, 1, 2, 0, 1, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 1, 2, 2], dtype=int32)

In [ ]:
Cluster0_2510=np.where(clust_labels_combine==0)
Cluster1_2510=np.where(clust_labels_combine==1)
Cluster2_2510=np.where(clust_labels_combine==2)

In [ ]:
np.save("/content/drive/MyDrive/J2/data/Cluster0_25.npy", Cluster0_25)
np.save("/content/drive/MyDrive/J2/data/Cluster1_25.npy", Cluster1_25)
np.save("/content/drive/MyDrive/J2/data/Cluster2_25.npy", Cluster2_25)

In [ ]:
np.save("/content/drive/MyDrive/J2/data/Cluster0_10.npy", Cluster0_10)
np.save("/content/drive/MyDrive/J2/data/Cluster1_10.npy", Cluster1_10)
np.save("/content/drive/MyDrive/J2/data/Cluster2_10.npy", Cluster2_10)

In [ ]:
np.save("/content/drive/MyDrive/J2/data/Cluster0_2510.npy", Cluster0_2510)
np.save("/content/drive/MyDrive/J2/data/Cluster1_2510.npy", Cluster1_2510)
np.save("/content/drive/MyDrive/J2/data/Cluster2_2510.npy", Cluster2_2510)

In [ ]:
dataapm25pm10