In [7]:
import numpy as np
# totaldata=np.load("/content/drive/MyDrive/J2/hourlytotalarray_withpm10.npy",allow_pickle=True)


In [ ]:
pm25=totaldata[:,:,0]
pm10=totaldata[:,:,-1]

In [ ]:
np.max(pm10)

318.812344234757

In [2]:
import pandas as pd
ar=pd.read_csv('C:/Users/vishn/OneDrive/Documents/BTP/FINAL/FINAL_LATITUDE_LONGITUDE.csv')
loc_b=pd.DataFrame(ar)

In [ ]:
meanpm25=np.mean(pm25,0)

In [ ]:
meanpm10=np.mean(pm10,0)

In [ ]:
meanpm10/meanpm25

array([1.9630863374855159, 2.167943665503659, 1.948233497471488,
       2.0309928990252506, 2.026519763224703, 2.0869193005738724,
       2.196737806255485, 2.5666259724438008, 1.9414037329269513,
       1.9460245467495456, 2.3380544291868013, 2.0328194578557204,
       2.1073933695112075, 2.3457839116726356, 1.6642184550416879,
       1.917804593494209, 1.9789176024373107, 1.7846574802556787,
       2.115338387281252, 1.9664791801942307, 1.8149197309568736,
       2.0849800561563883, 2.267607937420634, 1.9546755797289457,
       2.0878519370124957, 1.764102512199602, 1.9498450022457734,
       2.1628899023195376, 1.7878981268492564, 1.8715347857489733,
       2.168735688247559, 2.006555301240389, 1.900383522295853,
       1.981601293915619, 2.679396930084914, 2.1444816650367677,
       2.007989942373017, 1.7081986895518106, 1.93336644479169,
       2.1670008245729147], dtype=object)

In [3]:
pm25csv=pd.read_csv('C:/Users/vishn/OneDrive/Documents/BTP/FINAL/FINALL/pm25_3hrs.csv')
# pm10mean=np.mean(np.asarray(pm10csv),0)

In [4]:
pm25csv=pm25csv.iloc[:,2:]

In [5]:
pm25csv

265.3333333  64.66634911  442.3253384  112.1666667  36.00004988  \
0      341.500000    63.000000   366.833333    79.666667    36.000043   
1      323.333333    66.749864   421.250000    69.500000    36.000036   
2      340.000000    48.500000   335.500000    93.833333    36.000029   
3      132.166667    39.166667   154.833333    59.500000    36.000022   
4      106.833333    46.166667   106.833333    32.833333    36.000015   
...           ...          ...          ...          ...          ...   
8762   570.181093    60.666667   570.181093   100.166667    73.839115   
8763   560.056228    38.666667   560.056228    63.333333    73.843433   
8764   553.358864    40.500000   553.358864    48.000000    73.847750   
8765   568.720781    46.666667   568.720781    33.666667    73.852068   
8766   574.388365    32.833333   574.388365    28.833333    73.856385   

      30.00000004  240.0333333  117.5666667  437.8333333  550.3766667  ...  \
0       30.000000   193.366667   116.783333   327.666667   619.490000  ...   
1       30.000000   181.566667   125.700000   427.000000   465.200000  ...   
2       30.000000   199.800000    65.483333   376.500000   304.130000  ...   
3       30.000000   146.000000    80.850000   169.666667   143.858333  ...   
4       30.000000    75.600000    62.766667   157.833333   122.298333  ...   
...           ...          ...          ...          ...          ...  ...   
8762    35.833333    53.308333    74.615000   448.888099   570.181093  ...   
8763    31.000000    62.525000    30.823333   449.155889   560.056228  ...   
8764    28.166667    44.766667    46.228333   449.423678   553.358864  ...   
8765    30.833333    43.100000    82.821667   449.691468   568.720781  ...   
8766    30.000000    53.183333   105.980833   449.959258   574.388365  ...   

      33.33333333  480.0833333  112.3333333  435.8333333       42.8  \
0       45.833333   424.850000   145.333333   343.166667  42.800000   
1       62.166667   453.066667   138.000000   422.916667  42.800000   
2       29.833333   354.066667   131.083333   387.333333  42.800000   
3       18.166667   106.916667    94.333333   159.583333  42.800000   
4       11.000000   109.683333    78.666667   122.916667  42.800000   
...           ...          ...          ...          ...        ...   
8762    42.003904    92.102500   105.333333   570.181093  57.005538   
8763    42.005045    79.440000    64.000000   560.056228  57.007159   
8764    42.006187    70.791667    55.000000   553.358864  57.008780   
8765    42.007328    61.658333    52.000000   568.720781  57.010401   
8766    42.008470    76.471667    50.333333   574.388365  57.012022   

      98.76666667  451.9166667          97  304.7460091  53.66666667  
0       60.516667   372.333333  149.000000   242.666667    46.666667  
1       38.550000   528.916667  154.333333   284.333333    53.666667  
2       38.466667   505.333333  132.333333   260.333333    54.333333  
3       42.233333   199.500000   96.000000   121.833333    54.500000  
4       56.983333   188.750000   97.333333   109.333333    69.000000  
...           ...          ...         ...          ...          ...  
8762    69.733333   570.181093   52.666667   130.166667    76.005337  
8763    28.340667   560.056228   62.666667   118.166667    76.006816  
8764    55.821000   553.358864   42.666667    98.166667    76.008296  
8765   129.900000   568.720781   39.666667    49.833333    76.009775  
8766   169.246667   574.388365   25.000000    30.666667    76.011255  

[8767 rows x 264 columns]

In [8]:
pm25mean=np.mean(np.asarray(pm25csv),0)

In [9]:
pm25mean

array([189.45984056,  30.75482199, 206.18189763,  58.48875561,
        32.78747686,  30.68610381,  81.88961066,  49.50088811,
       130.84361162, 106.85634813,  32.56912515, 106.8877385 ,
        31.32856593,  50.47511738,  39.97168195, 175.16170412,
        48.31976902,  39.79530595,  39.50120136,  33.73639172,
        36.50810099,  31.41363422,  61.89362548,  58.44414512,
        30.10766749,  30.99032055,  73.61954101,  36.9907717 ,
        97.47566609,  35.83912193,  36.59332174,  43.3150912 ,
        29.38353803,  42.69629615,  66.7042304 ,  70.73569916,
        27.67759559, 156.6604373 , 103.95949791,  56.35855528,
        28.12113313,  14.41456502,  95.58081448, 235.79998667,
        73.76512127, 149.22982384, 189.8875906 ,  96.67008785,
        52.45821684, 276.28121235,  31.85967957,  37.77644386,
        74.97018174,  36.07421499,  43.73832341,  73.43580395,
        58.81164972,  48.72083397,  51.47753987,  80.29199314,
        56.46130431,  58.88938209,  77.7881615 ,  42.81

In [12]:
pm25new=[]
for i in range(26280):
  s=2*i
  # print(s)
  new=np.expand_dims(np.mean(pm25csv[s:s+2],axis=0),axis=0)
  pm25new.append(new)
pm25new=np.concatenate(pm25new,0)

In [13]:
pm25mean1=np.mean(pm25new,0)
pm25mean1

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, na

In [ ]:
def doKmeans(X, nclust=8):
    model = KMeans(nclust)
    model.fit(X)
    clust_labels = model.predict(X)
    cent = model.cluster_centers_
    return (clust_labels, cent)

clust_labels, cent = doKmeans(pm25, 3)
# kmeans = pd.DataFrame(clust_labels)
# print(kmeans)
pm["kmeans"]=clust_labels

In [ ]:
latlon=loc_b.iloc[:,1:]

In [ ]:
meanpm25.shape

(40,)

In [ ]:
dataapm25=np.concatenate([np.asarray(latlon),np.expand_dims(meanpm25,-1)],-1)

In [ ]:
dataapm10=np.concatenate([np.asarray(latlon),np.expand_dims(meanpm10,-1)],-1)

In [ ]:
dataapm25pm10=np.concatenate([dataapm10,np.expand_dims(meanpm25,-1)],-1)

In [ ]:
 from sklearn.cluster import KMeans

In [ ]:
def doKmeans(X, nclust=8):
    model = KMeans(nclust)
    model.fit(X)
    clust_labels = model.predict(X)
    cent = model.cluster_centers_
    return (clust_labels, cent)

clust_labels, cent = doKmeans(dataapm10, 3)
# kmeans = pd.DataFrame(clust_labels)
# print(kmeans)
# pm["kmeans"]=clust_labels

/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [ ]:
clust_labels1, cent = doKmeans(dataapm25, 3)
clust_labels1

/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


array([2, 1, 1, 0, 1, 2, 2, 2, 1, 2, 2, 2, 0, 0, 1, 1, 2, 0, 0, 2, 2, 1,
       2, 0, 1, 1, 2, 2, 1, 1, 2, 0, 2, 1, 0, 2, 1, 0, 1, 1], dtype=int32)

In [ ]:
Cluster0_25=np.where(clust_labels1==0)
Cluster1_25=np.where(clust_labels1==1)
Cluster2_25=np.where(clust_labels1==2)


In [ ]:
Cluster0_10=np.where(clust_labels==0)
Cluster1_10=np.where(clust_labels==1)
Cluster2_10=np.where(clust_labels==2)

In [ ]:
clust_labels

array([1, 2, 1, 0, 2, 1, 1, 2, 1, 0, 2, 1, 0, 1, 0, 2, 0, 0, 0, 1, 0, 2,
       1, 0, 2, 1, 0, 1, 1, 1, 1, 0, 1, 2, 1, 1, 1, 0, 1, 2], dtype=int32)

In [ ]:
clust_labels_combine, cent = doKmeans(dataapm25pm10, 3)
clust_labels_combine

/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


array([0, 2, 0, 1, 2, 0, 0, 0, 0, 1, 2, 0, 1, 0, 1, 2, 1, 1, 1, 0, 1, 2,
       0, 1, 2, 0, 1, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 1, 2, 2], dtype=int32)

In [ ]:
Cluster0_2510=np.where(clust_labels_combine==0)
Cluster1_2510=np.where(clust_labels_combine==1)
Cluster2_2510=np.where(clust_labels_combine==2)

In [ ]:
np.save("/content/drive/MyDrive/J2/data/Cluster0_25.npy", Cluster0_25)
np.save("/content/drive/MyDrive/J2/data/Cluster1_25.npy", Cluster1_25)
np.save("/content/drive/MyDrive/J2/data/Cluster2_25.npy", Cluster2_25)

In [ ]:
np.save("/content/drive/MyDrive/J2/data/Cluster0_10.npy", Cluster0_10)
np.save("/content/drive/MyDrive/J2/data/Cluster1_10.npy", Cluster1_10)
np.save("/content/drive/MyDrive/J2/data/Cluster2_10.npy", Cluster2_10)

In [ ]:
np.save("/content/drive/MyDrive/J2/data/Cluster0_2510.npy", Cluster0_2510)
np.save("/content/drive/MyDrive/J2/data/Cluster1_2510.npy", Cluster1_2510)
np.save("/content/drive/MyDrive/J2/data/Cluster2_2510.npy", Cluster2_2510)

In [ ]:
dataapm25pm10